# Generated by Django 4.2.5 on 2023-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Comprador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
