# Generated by Django 4.2.5 on 2023-12-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Comprador', '0002_alter_comprador_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='primernombre',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='usuario',
        ),
    ]
