# Generated by Django 4.2.5 on 2023-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Comprador', '0003_remove_comprador_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
