# Generated by Django 4.2.5 on 2023-11-19 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Carrito_de_Compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Targeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTargeta', models.CharField(max_length=16)),
                ('codigoSeguridad', models.CharField(max_length=3)),
                ('fechaExpiracion', models.DateField()),
                ('nombreTitular', models.CharField(max_length=100)),
                ('bancoAdquiriente', models.CharField(max_length=50)),
                ('idFormaPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pago_y_Compras.formapago')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField()),
                ('montoTotal', models.FloatField()),
                ('direccionEnvio', models.CharField(max_length=100)),
                ('numeroSeguimiento', models.CharField(max_length=10)),
                ('observaciones', models.TextField(max_length=100)),
                ('formaPagoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pago_y_Compras.formapago')),
                ('idCarritoCompras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito_de_Compras.carritocompra')),
                ('idComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
