# Generated by Django 4.2.5 on 2023-12-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pago_y_Compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Targeta',
            new_name='Tarjeta',
        ),
    ]
