# Generated by Django 4.2.5 on 2023-11-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('historia', models.TextField(max_length=1000)),
                ('correo_electronico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('contrasena', models.CharField(max_length=8)),
                ('id_informacion_publica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_de_Usuarios_tipo_Artesanos.informacionpublica')),
            ],
        ),
    ]
