# Generated by Django 4.2.5 on 2023-12-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Artesanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('contrasena', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('historia', models.TextField(max_length=1000)),
                ('correo_electronico', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='InformacionPrivada',
        ),
    ]
