# Generated by Django 4.2.5 on 2023-12-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Artesanos', '0003_delete_informacionpublica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artesano',
            old_name='contrasena',
            new_name='contraseña',
        ),
    ]
