# Generated by Django 4.2.5 on 2023-11-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Artesanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.CharField(max_length=300)),
                ('proceso_creativo', models.CharField(max_length=50)),
                ('id_artesano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_de_Usuarios_tipo_Artesanos.informacionpublica')),
            ],
        ),
    ]
