# Generated by Django 4.2.5 on 2023-12-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_de_Usuarios_tipo_Artesanos', '0002_artesano_delete_informacionprivada'),
        ('Gestion_de_Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='id_artesano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_de_Usuarios_tipo_Artesanos.artesano'),
        ),
    ]
