# Generated by Django 4.2.5 on 2023-11-19 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_de_Inventario', '0001_initial'),
        ('Gestion_de_Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='id_comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reseña',
            name='id_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_de_Inventario.obra'),
        ),
    ]
