# Generated by Django 4.2.5 on 2023-11-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pago_y_Compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_venta', models.DateTimeField(auto_now_add=True)),
                ('total_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pago_y_Compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(max_length=2000)),
                ('id_Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pago_y_Compras.compra')),
            ],
        ),
    ]
